export const actionTypes = {
  INCREMENT_REQUESTED: 'counter/INCREMENT_REQUESTED',
  INCREMENT: 'counter/INCREMENT',
  DECREMENT_REQUESTED: 'counter/DECREMENT_REQUESTED',
  DECREMENT: 'counter/DECREMENT',
}