export const API_URL = 'http://192.168.3.189:3000/trigger'

export const actionTypes = {
  INCREMENT_REQUESTED: 'counter/INCREMENT_REQUESTED',
  INCREMENT: 'counter/INCREMENT',
  DECREMENT_REQUESTED: 'counter/DECREMENT_REQUESTED',
  DECREMENT: 'counter/DECREMENT',

  GET_TRIGGER_SUCCESS: 'GET_TRIGGER_SUCCESS',
  GET_TRIGGER_FAILURE: 'GET_TRIGGER_FAILURE',
  GET_TRIGGER_REQUEST: 'GET_TRIGGER_REQUEST',
}